
-- periodic player state update

local state_ready = false

AddEventHandler("playerSpawned",function() -- delay state recording
  state_ready = false
  
  Citizen.CreateThread(function()
    Citizen.Wait(30000)
    state_ready = true
  end)
end)

Citizen.CreateThread(function()
  while true do
    Citizen.Wait(30000)

    if IsPlayerPlaying(PlayerId()) and state_ready then
      local x,y,z = table.unpack(GetEntityCoords(GetPlayerPed(-1),true))
      vRPserver.ping({})
      vRPserver.updatePos({x,y,z})
      vRPserver.updateHealth({tvRP.getHealth()})
      vRPserver.updateWeapons({tvRP.getWeapons()})
      vRPserver.updateCustomization({tvRP.getCustomization()})
    end
  end
end)

-- WEAPONS

-- def
local weapon_types = {
  "GADGET_PARACHUTE",
  "WEAPON_ADVANCEDRIFLE",
  "WEAPON_AIRSTRIKE_ROCKET",
  "WEAPON_APPISTOL",
  "WEAPON_ASSAULTRIFLE",
  "WEAPON_ASSAULTRIFLE_MK2",
  "WEAPON_ASSAULTSHOTGUN",
  "WEAPON_ASSAULTSMG",
  "WEAPON_AUTOSHOTGUN",
  "WEAPON_BALL",
  "WEAPON_BAT",
  "WEAPON_BATTLEAXE",
  "WEAPON_BOTTLE",
  "WEAPON_BRIEFCASE",
  "WEAPON_BRIEFCASE_02",
  "WEAPON_BULLPUPRIFLE",
  "WEAPON_BULLPUPSHOTGUN",
  "WEAPON_BZGAS",
  "WEAPON_CARBINERIFLE",
  "WEAPON_CARBINERIFLE_MK2",
  "WEAPON_COMBATMG",
  "WEAPON_COMBATMG_MK2",
  "WEAPON_COMBATPDW",
  "WEAPON_COMBATPISTOL",
  "WEAPON_COMPACTLAUNCHER",
  "WEAPON_COMPACTRIFLE",
  "WEAPON_CROWBAR",
  "WEAPON_DAGGER",
  "WEAPON_DBSHOTGUN",
  "WEAPON_DIGISCANNER",
  "WEAPON_FIREEXTINGUISHER",
  "WEAPON_FIREWORK",
  "WEAPON_FLARE",
  "WEAPON_FLAREGUN",
  "WEAPON_FLASHLIGHT",
  "WEAPON_GOLFCLUB",
  "WEAPON_GRENADE",
  "WEAPON_GRENADELAUNCHER",
  "WEAPON_GRENADELAUNCHER_SMOKE",
  "WEAPON_GUSENBERG",
  "WEAPON_HAMMER",
  "WEAPON_HATCHET",
  "WEAPON_HEAVYPISTOL",
  "WEAPON_HEAVYSHOTGUN",
  "WEAPON_HEAVYSNIPER",
  "WEAPON_HEAVYSNIPER_MK2",
  "WEAPON_HOMINGLAUNCHER",
  "WEAPON_KNIFE",
  "WEAPON_KNUCKLE",
  "WEAPON_MACHETE",
  "WEAPON_MACHINEPISTOL",
  "WEAPON_MARKSMANPISTOL",
  "WEAPON_MARKSMANRIFLE",
  "WEAPON_MG",
  "WEAPON_MICROSMG",
  "WEAPON_MINIGUN",
  "WEAPON_MINISMG",
  "WEAPON_MOLOTOV",
  "WEAPON_MUSKET",
  "WEAPON_NIGHTSTICK",
  "WEAPON_PASSENGER_ROCKET",
  "WEAPON_PETROLCAN",
  "WEAPON_PIPEBOMB",
  "WEAPON_PISTOL",
  "WEAPON_PISTOL_MK2",
  "WEAPON_PISTOL50",
  "WEAPON_POOLCUE",
  "WEAPON_PROXMINE",
  "WEAPON_PUMPSHOTGUN",
  "WEAPON_RAILGUN",
  "WEAPON_REMOTESNIPER",
  "WEAPON_REVOLVER",
  "WEAPON_RPG",
  "WEAPON_SAWNOFFSHOTGUN",
  "WEAPON_SMG",
  "WEAPON_SMG_MK2",
  "WEAPON_SMOKEGRENADE",
  "WEAPON_SNIPERRIFLE",
  "WEAPON_SNOWBALL",
  "WEAPON_SNSPISTOL",
  "WEAPON_SPECIALCARBINE",
  "WEAPON_STICKYBOMB",
  "WEAPON_STINGER",
  "WEAPON_STUNGUN",
  "WEAPON_SWITCHBLADE",
  "WEAPON_VINTAGEPISTOL",
  "WEAPON_WRENCH"
}

local weapon_components = {
  "COMPONENT_KNUCKLE_VARMOD_BASE",
  "COMPONENT_KNUCKLE_VARMOD_PIMP",
  "COMPONENT_KNUCKLE_VARMOD_BALLAS",
  "COMPONENT_KNUCKLE_VARMOD_DOLLAR",
  "COMPONENT_KNUCKLE_VARMOD_DIAMOND",
  "COMPONENT_KNUCKLE_VARMOD_HATE",
  "COMPONENT_KNUCKLE_VARMOD_LOVE",
  "COMPONENT_KNUCKLE_VARMOD_PLAYER",
  "COMPONENT_KNUCKLE_VARMOD_KING",
  "COMPONENT_KNUCKLE_VARMOD_VAGOS",
  "COMPONENT_SWITCHBLADE_VARMOD_BASE",
  "COMPONENT_SWITCHBLADE_VARMOD_VAR1",
  "COMPONENT_SWITCHBLADE_VARMOD_VAR2",
  "COMPONENT_PISTOL_CLIP_01",
  "COMPONENT_PISTOL_CLIP_02",
  "COMPONENT_AT_PI_FLSH",
  "COMPONENT_AT_PI_SUPP_02",
  "COMPONENT_PISTOL_VARMOD_LUXE",
  "COMPONENT_COMBATPISTOL_CLIP_01",
  "COMPONENT_COMBATPISTOL_CLIP_02",
  "COMPONENT_AT_PI_SUPP",
  "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER",
  "COMPONENT_APPISTOL_CLIP_01",
  "COMPONENT_APPISTOL_CLIP_02",
  "COMPONENT_APPISTOL_VARMOD_LUXE",
  "COMPONENT_PISTOL50_CLIP_01",
  "COMPONENT_PISTOL50_CLIP_02",
  "COMPONENT_AT_AR_SUPP_02",
  "COMPONENT_PISTOL50_VARMOD_LUXE",
  "COMPONENT_REVOLVER_VARMOD_BOSS",
  "COMPONENT_REVOLVER_VARMOD_GOON",
  "COMPONENT_REVOLVER_CLIP_01",
  "COMPONENT_SNSPISTOL_CLIP_01",
  "COMPONENT_SNSPISTOL_CLIP_02",
  "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER",
  "COMPONENT_HEAVYPISTOL_CLIP_01",
  "COMPONENT_HEAVYPISTOL_CLIP_02",
  "COMPONENT_HEAVYPISTOL_VARMOD_LUXE",
  "COMPONENT_REVOLVER_MK2_CLIP_01",
  "COMPONENT_REVOLVER_MK2_CLIP_TRACER",
  "COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY",
  "COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT",
  "COMPONENT_REVOLVER_MK2_CLIP_FMJ",
  "COMPONENT_AT_SIGHTS",
  "COMPONENT_AT_SCOPE_MACRO_MK2",
  "COMPONENT_AT_PI_COMP_03",
  "COMPONENT_REVOLVER_MK2_CAMO",
  "COMPONENT_REVOLVER_MK2_CAMO_02",
  "COMPONENT_REVOLVER_MK2_CAMO_03",
  "COMPONENT_REVOLVER_MK2_CAMO_04",
  "COMPONENT_REVOLVER_MK2_CAMO_05",
  "COMPONENT_REVOLVER_MK2_CAMO_06",
  "COMPONENT_REVOLVER_MK2_CAMO_07",
  "COMPONENT_REVOLVER_MK2_CAMO_08",
  "COMPONENT_REVOLVER_MK2_CAMO_09",
  "COMPONENT_REVOLVER_MK2_CAMO_10",
  "COMPONENT_REVOLVER_MK2_CAMO_IND_01",
  "COMPONENT_SNSPISTOL_MK2_CLIP_01",
  "COMPONENT_SNSPISTOL_MK2_CLIP_02",
  "COMPONENT_SNSPISTOL_MK2_CLIP_TRACER",
  "COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY",
  "COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT",
  "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ",
  "COMPONENT_AT_PI_FLSH_03",
  "COMPONENT_AT_PI_RAIL_02",
  "COMPONENT_AT_PI_COMP_02",
  "COMPONENT_SNSPISTOL_MK2_CAMO",
  "COMPONENT_SNSPISTOL_MK2_CAMO_02",
  "COMPONENT_SNSPISTOL_MK2_CAMO_03",
  "COMPONENT_SNSPISTOL_MK2_CAMO_04",
  "COMPONENT_SNSPISTOL_MK2_CAMO_05",
  "COMPONENT_SNSPISTOL_MK2_CAMO_06",
  "COMPONENT_SNSPISTOL_MK2_CAMO_07",
  "COMPONENT_SNSPISTOL_MK2_CAMO_08",
  "COMPONENT_SNSPISTOL_MK2_CAMO_09",
  "COMPONENT_SNSPISTOL_MK2_CAMO_10",
  "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01",
  "COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE",
  "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE",
  "COMPONENT_PISTOL_MK2_CLIP_01",
  "COMPONENT_PISTOL_MK2_CLIP_02",
  "COMPONENT_PISTOL_MK2_CLIP_TRACER",
  "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY",
  "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT",
  "COMPONENT_PISTOL_MK2_CLIP_FMJ",
  "COMPONENT_AT_PI_RAIL",
  "COMPONENT_AT_PI_FLSH_02",
  "COMPONENT_AT_PI_COMP",
  "COMPONENT_PISTOL_MK2_CAMO",
  "COMPONENT_PISTOL_MK2_CAMO_02",
  "COMPONENT_PISTOL_MK2_CAMO_03",
  "COMPONENT_PISTOL_MK2_CAMO_04",
  "COMPONENT_PISTOL_MK2_CAMO_05",
  "COMPONENT_PISTOL_MK2_CAMO_06",
  "COMPONENT_PISTOL_MK2_CAMO_07",
  "COMPONENT_PISTOL_MK2_CAMO_08",
  "COMPONENT_PISTOL_MK2_CAMO_09",
  "COMPONENT_PISTOL_MK2_CAMO_10",
  "COMPONENT_PISTOL_MK2_CAMO_IND_01",
  "COMPONENT_PISTOL_MK2_CAMO_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_02_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_03_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_04_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_05_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_06_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_07_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_08_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_09_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_10_SLIDE",
  "COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE",
  "COMPONENT_VINTAGEPISTOL_CLIP_01",
  "COMPONENT_VINTAGEPISTOL_CLIP_02",
  "COMPONENT_RAYPISTOL_VARMOD_XMAS18",
  "COMPONENT_CERAMICPISTOL_CLIP_01",
  "COMPONENT_CERAMICPISTOL_CLIP_02",
  "COMPONENT_CERAMICPISTOL_SUPP",
  "COMPONENT_MICROSMG_CLIP_01",
  "COMPONENT_MICROSMG_CLIP_02",
  "COMPONENT_AT_SCOPE_MACRO",
  "COMPONENT_MICROSMG_VARMOD_LUXE",
  "COMPONENT_SMG_CLIP_01",
  "COMPONENT_SMG_CLIP_02",
  "COMPONENT_SMG_CLIP_03",
  "COMPONENT_AT_AR_FLSH",
  "COMPONENT_AT_SCOPE_MACRO_02",
  "COMPONENT_SMG_VARMOD_LUXE",
  "COMPONENT_ASSAULTSMG_CLIP_01",
  "COMPONENT_ASSAULTSMG_CLIP_02",
  "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER",
  "COMPONENT_MINISMG_CLIP_01",
  "COMPONENT_MINISMG_CLIP_02",
  "COMPONENT_SMG_MK2_CLIP_01",
  "COMPONENT_SMG_MK2_CLIP_02",
  "COMPONENT_SMG_MK2_CLIP_TRACER",
  "COMPONENT_SMG_MK2_CLIP_INCENDIARY",
  "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT",
  "COMPONENT_SMG_MK2_CLIP_FMJ",
  "COMPONENT_AT_SIGHTS_SMG",
  "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2",
  "COMPONENT_AT_SCOPE_SMALL_SMG_MK2",
  "COMPONENT_AT_MUZZLE_01",
  "COMPONENT_AT_MUZZLE_02",
  "COMPONENT_AT_MUZZLE_03",
  "COMPONENT_AT_MUZZLE_04",
  "COMPONENT_AT_MUZZLE_05",
  "COMPONENT_AT_MUZZLE_06",
  "COMPONENT_AT_MUZZLE_07",
  "COMPONENT_AT_SB_BARREL_01",
  "COMPONENT_AT_SB_BARREL_02",
  "COMPONENT_SMG_MK2_CAMO",
  "COMPONENT_SMG_MK2_CAMO_02",
  "COMPONENT_SMG_MK2_CAMO_03",
  "COMPONENT_SMG_MK2_CAMO_04",
  "COMPONENT_SMG_MK2_CAMO_05",
  "COMPONENT_SMG_MK2_CAMO_06",
  "COMPONENT_SMG_MK2_CAMO_07",
  "COMPONENT_SMG_MK2_CAMO_08",
  "COMPONENT_SMG_MK2_CAMO_09",
  "COMPONENT_SMG_MK2_CAMO_10",
  "COMPONENT_SMG_MK2_CAMO_IND_01",
  "COMPONENT_MACHINEPISTOL_CLIP_01",
  "COMPONENT_MACHINEPISTOL_CLIP_02",
  "COMPONENT_MACHINEPISTOL_CLIP_03",
  "COMPONENT_COMBATPDW_CLIP_01",
  "COMPONENT_COMBATPDW_CLIP_02",
  "COMPONENT_COMBATPDW_CLIP_03",
  "COMPONENT_AT_AR_AFGRIP",
  "COMPONENT_AT_SR_SUPP",
  "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER",
  "COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE",
  "COMPONENT_ASSAULTSHOTGUN_CLIP_01",
  "COMPONENT_ASSAULTSHOTGUN_CLIP_02",
  "COMPONENT_AT_AR_SUPP",
  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_01",
  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY",
  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING",
  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT",
  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE",
  "COMPONENT_AT_SR_SUPP_03",
  "COMPONENT_AT_MUZZLE_08",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_02",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_03",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_04",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_05",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_06",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_07",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_08",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_09",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_10",
  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01",
  "COMPONENT_HEAVYSHOTGUN_CLIP_01",
  "COMPONENT_HEAVYSHOTGUN_CLIP_02",
  "COMPONENT_HEAVYSHOTGUN_CLIP_03",
  "COMPONENT_ASSAULTRIFLE_CLIP_01",
  "COMPONENT_ASSAULTRIFLE_CLIP_02",
  "COMPONENT_ASSAULTRIFLE_CLIP_03",
  "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE",
  "COMPONENT_CARBINERIFLE_CLIP_01",
  "COMPONENT_CARBINERIFLE_CLIP_02",
  "COMPONENT_CARBINERIFLE_CLIP_03",
  "COMPONENT_AT_SCOPE_MEDIUM",
  "COMPONENT_CARBINERIFLE_VARMOD_LUXE",
  "COMPONENT_ADVANCEDRIFLE_CLIP_01",
  "COMPONENT_ADVANCEDRIFLE_CLIP_02",
  "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE",
  "COMPONENT_SPECIALCARBINE_CLIP_01",
  "COMPONENT_SPECIALCARBINE_CLIP_02",
  "COMPONENT_SPECIALCARBINE_CLIP_03",
  "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER",
  "COMPONENT_BULLPUPRIFLE_CLIP_01",
  "COMPONENT_BULLPUPRIFLE_CLIP_02",
  "COMPONENT_BULLPUPRIFLE_VARMOD_LOW",
  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_01",
  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02",
  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER",
  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY",
  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING",
  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ",
  "COMPONENT_AT_SCOPE_MACRO_02_MK2",
  "COMPONENT_AT_SCOPE_SMALL_MK2",
  "COMPONENT_AT_BP_BARREL_01",
  "COMPONENT_AT_BP_BARREL_02",
  "COMPONENT_AT_AR_AFGRIP_02",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_02",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_03",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_04",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_05",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_06",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_07",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_08",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_09",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_10",
  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01",
  "COMPONENT_SPECIALCARBINE_MK2_CLIP_01",
  "COMPONENT_SPECIALCARBINE_MK2_CLIP_02",
  "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER",
  "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY",
  "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING",
  "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ",
  "COMPONENT_AT_SCOPE_MEDIUM_MK2",
  "COMPONENT_AT_SC_BARREL_01",
  "COMPONENT_AT_SC_BARREL_02",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_02",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_03",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_04",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_05",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_06",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_07",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_08",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_09",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_10",
  "COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01",
  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01",
  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02",
  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER",
  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY",
  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING",
  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ",
  "COMPONENT_AT_AR_BARREL_01",
  "COMPONENT_AT_AR_BARREL_02",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_02",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_03",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_04",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_05",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_06",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_07",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_08",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_09",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_10",
  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01",
  "COMPONENT_CARBINERIFLE_MK2_CLIP_01",
  "COMPONENT_CARBINERIFLE_MK2_CLIP_02",
  "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER",
  "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY",
  "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING",
  "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ",
  "COMPONENT_AT_CR_BARREL_01",
  "COMPONENT_AT_CR_BARREL_02",
  "COMPONENT_CARBINERIFLE_MK2_CAMO",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_02",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_03",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_04",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_05",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_06",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_07",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_08",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_09",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_10",
  "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01",
  "COMPONENT_COMPACTRIFLE_CLIP_01",
  "COMPONENT_COMPACTRIFLE_CLIP_02",
  "COMPONENT_COMPACTRIFLE_CLIP_03",
  "COMPONENT_MILITARYRIFLE_CLIP_01",
  "COMPONENT_MILITARYRIFLE_CLIP_02",
  "COMPONENT_MILITARYRIFLE_SIGHT_01",
  "COMPONENT_MG_CLIP_01",
  "COMPONENT_MG_CLIP_02",
  "COMPONENT_AT_SCOPE_SMALL_02",
  "COMPONENT_MG_VARMOD_LOWRIDER",
  "COMPONENT_COMBATMG_CLIP_01",
  "COMPONENT_COMBATMG_CLIP_02",
  "COMPONENT_COMBATMG_VARMOD_LOWRIDER",
  "COMPONENT_COMBATMG_MK2_CLIP_01",
  "COMPONENT_COMBATMG_MK2_CLIP_02",
  "COMPONENT_COMBATMG_MK2_CLIP_TRACER",
  "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY",
  "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING",
  "COMPONENT_COMBATMG_MK2_CLIP_FMJ",
  "COMPONENT_AT_MG_BARREL_01",
  "COMPONENT_AT_MG_BARREL_02",
  "COMPONENT_COMBATMG_MK2_CAMO",
  "COMPONENT_COMBATMG_MK2_CAMO_02",
  "COMPONENT_COMBATMG_MK2_CAMO_03",
  "COMPONENT_COMBATMG_MK2_CAMO_04",
  "COMPONENT_COMBATMG_MK2_CAMO_05",
  "COMPONENT_COMBATMG_MK2_CAMO_06",
  "COMPONENT_COMBATMG_MK2_CAMO_07",
  "COMPONENT_COMBATMG_MK2_CAMO_08",
  "COMPONENT_COMBATMG_MK2_CAMO_09",
  "COMPONENT_COMBATMG_MK2_CAMO_10",
  "COMPONENT_COMBATMG_MK2_CAMO_IND_01",
  "COMPONENT_GUSENBERG_CLIP_01",
  "COMPONENT_GUSENBERG_CLIP_02",
  "COMPONENT_SNIPERRIFLE_CLIP_01",
  "COMPONENT_AT_SCOPE_LARGE",
  "COMPONENT_AT_SCOPE_MAX",
  "COMPONENT_SNIPERRIFLE_VARMOD_LUXE",
  "COMPONENT_HEAVYSNIPER_CLIP_01",
  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_01",
  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02",
  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER",
  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY",
  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING",
  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ",
  "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2",
  "COMPONENT_AT_MRFL_BARREL_01",
  "COMPONENT_AT_MRFL_BARREL_02",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_02",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_03",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_04",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_05",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_06",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_07",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_08",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_09",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_10",
  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01",
  "COMPONENT_HEAVYSNIPER_MK2_CLIP_01",
  "COMPONENT_HEAVYSNIPER_MK2_CLIP_02",
  "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY",
  "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING",
  "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ",
  "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE",
  "COMPONENT_AT_SCOPE_LARGE_MK2",
  "COMPONENT_AT_SCOPE_NV",
  "COMPONENT_AT_SCOPE_THERMAL",
  "COMPONENT_AT_MUZZLE_09",
  "COMPONENT_AT_SR_BARREL_01",
  "COMPONENT_AT_SR_BARREL_02",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_02",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_03",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_04",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_05",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_06",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_07",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_08",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_09",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_10",
  "COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01",
  "COMPONENT_MARKSMANRIFLE_CLIP_01",
  "COMPONENT_MARKSMANRIFLE_CLIP_02",
  "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM",
  "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE",
  "COMPONENT_GRENADELAUNCHER_CLIP_01",
  "COMPONENT_AT_SCOPE_SMALL",
}

function tvRP.getWeaponTypes()
  return weapon_types
end

function tvRP.getWeapons()
  local player = GetPlayerPed(-1)

  local ammo_types = {} -- remember ammo type to not duplicate ammo amount

  local weapons = {}
  for k,v in pairs(weapon_types) do
    local model = string.upper(v)
    local hash = GetHashKey(model)
    if HasPedGotWeapon(player,hash) then
      local weapon = {}

      weapons[v] = weapon

      local atype = Citizen.InvokeNative(0x7FEAD38B326B9F74, player, hash)
      if ammo_types[atype] == nil then
        ammo_types[atype] = true
        weapon.ammo = GetAmmoInPedWeapon(player,hash)
      else
        weapon.ammo = 0
      end

      weapon.components = {}

      for k,v in pairs(weapon_components) do
        if HasPedGotWeaponComponent(player, hash, v) then
          table.insert(weapon.components, v)
        end
      end
    
      weapons[model] = weapon
    end
  end

  return weapons
end

-- replace weapons (combination of getWeapons and giveWeapons)
-- return previous weapons
function tvRP.replaceWeapons(weapons)
  local old_weapons = tvRP.getWeapons()
  tvRP.giveWeapons({weapons}, true)
  return old_weapons
end

function tvRP.giveWeapons(weapons,clear_before)
  local player = GetPlayerPed(-1)

  -- give weapons to player

  if clear_before then
    RemoveAllPedWeapons(player,true)
  end

  for k,weapon in pairs(weapons) do
    local hash = GetHashKey(k)
    local ammo = weapon.ammo or 0
    local components = weapon.components

    GiveWeaponToPed(player, hash, ammo, false)

    if components ~= nil then
      for k,v in pairs(components) do
        GiveWeaponComponentToPed(player, hash, v)
      end
    end

  end
end

function tvRP.removeWeapons(weapons)
  local player = GetPlayerPed(-1)

  -- remove weapons from player

  for k,weapon in pairs(weapons) do
    local hash = GetHashKey(k)

    RemoveWeaponFromPed(player, hash)
  end
end

--[[
function tvRP.dropWeapon()
  SetPedDropsWeapon(GetPlayerPed(-1))
end
--]]

-- PLAYER CUSTOMIZATION

-- parse part key (a ped part or a prop part)
-- return is_proppart, index
local function parse_part(key)
  if type(key) == "string" and string.sub(key,1,1) == "p" then
    return true,tonumber(string.sub(key,2))
  else
    return false,tonumber(key)
  end
end

function tvRP.getDrawables(part)
  local isprop, index = parse_part(part)
  if isprop then
    return GetNumberOfPedPropDrawableVariations(GetPlayerPed(-1),index)
  else
    return GetNumberOfPedDrawableVariations(GetPlayerPed(-1),index)
  end
end

function tvRP.getDrawableTextures(part, drawable)
  local isprop, index = parse_part(part)
  if isprop then
    return GetNumberOfPedPropTextureVariations(GetPlayerPed(-1),index,drawable)
  else
    return GetNumberOfPedTextureVariations(GetPlayerPed(-1),index,drawable)
  end
end

function tvRP.getCustomization()
  local ped = GetPlayerPed(-1)

  local custom = {}

  custom.modelhash = GetEntityModel(ped)

  -- ped parts
  for i=0,20 do -- index limit to 20
    custom[i] = {GetPedDrawableVariation(ped,i), GetPedTextureVariation(ped,i), GetPedPaletteVariation(ped,i)}
  end

  -- props
  for i=0,10 do -- index limit to 10
    custom["p"..i] = {GetPedPropIndex(ped,i), math.max(GetPedPropTextureIndex(ped,i),0)}
  end

  return custom
end

-- partial customization (only what is set is changed)
function tvRP.setCustomization(custom) -- indexed [drawable,texture,palette] components or props (p0...) plus .modelhash or .model
  local exit = TUNNEL_DELAYED() -- delay the return values

  Citizen.CreateThread(function() -- new thread
    if custom then
      local ped = GetPlayerPed(-1)
      local mhash = nil

      -- model
      if custom.modelhash ~= nil then
        mhash = custom.modelhash
      elseif custom.model ~= nil then
        mhash = GetHashKey(custom.model)
      end

      if mhash ~= nil then
        local i = 0
        while not HasModelLoaded(mhash) and i < 10000 do
          RequestModel(mhash)
          Citizen.Wait(10)
        end

        if HasModelLoaded(mhash) then
          -- changing player model remove weapons, so save it
          local weapons = tvRP.getWeapons()
          SetPlayerModel(PlayerId(), mhash)
          tvRP.giveWeapons(weapons,true)
          SetModelAsNoLongerNeeded(mhash)
        end
      end

      ped = GetPlayerPed(-1)

      -- parts
      for k,v in pairs(custom) do
        if k ~= "model" and k ~= "modelhash" then
          local isprop, index = parse_part(k)
          if isprop then
            if v[1] < 0 then
              ClearPedProp(ped,index)
            else
              SetPedPropIndex(ped,index,v[1],v[2],v[3] or 2)
            end
          else
            SetPedComponentVariation(ped,index,v[1],v[2],v[3] or 2)
          end
        end
      end
    end

    exit({})
  end)
end
